// Generated by CoffeeScript 1.12.7
(function() {
  window.onload = function() {
    window.castRecieverManager = cast.receiver.CastReceiverManager.getInstance();
    console.log('Receiver manager starting');
    castReceiverManager.onReady = function(event) {
      console.log(Received Ready event: #{JSON.stringify event.data});
      return window.castReceiverManager.setApplicationState('casting is ready');
    };
    castReceiverManager.onSenderConnected = function(event) {
      return console.log("Received Sender Connected event: " + event.senderId);
    };
    castReceiverManager.onSenderDisconnected = function(event) {
      return console.log("Received Sender Disconnected event: " + event.senderId);
    };
    window.messageBus = window.castReceiverManager.getCastMessageBus('urn:x-cast:io.github.kjxlstad', cast.receiver.CastMessageBus.MessageType.JSON);
    window.messageBus.onMessage = function(event) {
      console.log("Message [" + event.senderId + "]: " + event.data);
      if (event.data['type'] === 'load') {
        return document.querySelector('#test').innerHTML = 'test working';
      }
    };
    window.castReceiverManager.start({
      statusText: 'Application is starting'
    });
    return console.log('Receiver Manager started');
  };

}).call(this);
